In [1]:
#importing numpy library
import numpy as np

In [3]:
print(np.cos(np.pi))

-1.0


In [4]:
print(np.sqrt(1.21))

1.1


In [5]:
print(np.log(np.exp(5.2)))

5.2


In [6]:
vec = np.array([1,2,3])
print(vec)

[1 2 3]


In [7]:
type(vec)

numpy.ndarray

In [10]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat)
print('')
mat1 = mat.transpose()
print(mat1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [14]:
vec2 = np.arange(0,15)
print(vec2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [15]:
vec3 = np.arange(0,20,3)
print(vec3)

[ 0  3  6  9 12 15 18]


In [17]:
vec4 = np.linspace(0,50,5)
print(vec4)

[ 0.  12.5 25.  37.5 50. ]


In [21]:
vec5 = np.linspace(0,100,10)
vec5

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [23]:
vec5.reshape(2,5)

array([[  0.        ,  11.11111111,  22.22222222,  33.33333333,
         44.44444444],
       [ 55.55555556,  66.66666667,  77.77777778,  88.88888889,
        100.        ]])

In [24]:
print(np.zeros((5,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [25]:
print(np.ones((3,5)))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [26]:
mat2 = np.eye(5)
print(mat2)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [34]:
matx = np.array([[1,2,1],[4,5,9],[1,8,9]])
print(matx)

[[1 2 1]
 [4 5 9]
 [1 8 9]]


In [35]:
vetx = np.array([1,2,3])
print(vetx)

[1 2 3]


In [36]:
product = np.matmul(matx,vetx)
print(product)

[ 8 41 44]


In [37]:
print(np.linalg.solve(matx,product))

[1. 2. 3.]


In [40]:
print(np.random.randn(5,5))

[[ 1.57105401  0.26969649 -0.72829364  1.24545104 -0.07349835]
 [ 0.15106895  0.39474942 -0.82426906 -0.53083908 -0.96522417]
 [-0.99029917 -0.51562216  0.17264378 -0.30884062  0.26789845]
 [-0.84798221 -0.04479175 -0.71124211  1.1351817   1.18838709]
 [-0.99514202  0.94224909  0.28202526 -1.13814934  0.97125468]]


In [41]:
vec= np.arange(10,20)
print(vec)

[10 11 12 13 14 15 16 17 18 19]


In [42]:
vec2=vec[np.arange(0,10,3)]
print(vec2)

[10 13 16 19]
